apiVersion: v1
kind: Pod
metadata:
  name: hello-world-pod
spec:
  containers:
  # 1. THE MAIN APP (The Deliverer)
  - name: web-server
    image: nginx:alpine
    volumeMounts:
    - name: workdir
      mountPath: /usr/share/nginx/html

  # 2. THE SIDECAR (The Creator)
  - name: message-generator
    image: alpine
    command: ["/bin/sh", "-c"]
    args: ["echo 'Hello from Sidecar' > /var/log/index.html; sleep 3600"]
    volumeMounts:
    - name: workdir
      mountPath: /var/log

  # 3. THE SHARED SPACE (The Bridge)
  volumes:
  - name: workdir
    emptyDir: {}